### ISSUE TITLE
Bundled dependency on Gnulib

### ISSUE THREAD

**Issue by anoopcs9** [gluster/glusterfs-coreutils#10]
Instead of using gnulib-tool from system libraries glusterfs-coreutils contains a special git sub module for Gnulib. Can we live with system libraries that provide gnulib-tool?

**Comment by anoopcs9** [comment]
I tried installing Gnulib on a fedora system and successfully compiled glusterfs-coreutils without the bundled dependency for the same within the source. It all went fine. I did some basic testing of commands without any failures.

At this point, I would like to remove this inbuilt dependency for Gnulib. If so, do we have a dependency for a particular version of Gnulib? On the other side is there a hidden reason for introducing Gnulib git submodule?

**Comment by craigcabrey** [comment]
The original reason I used a submodule was because I got the impression that gnulib was meant to be a source level dependency. Straight from the [site](https://www.gnu.org/software/gnulib/):

> Gnulib takes a different approach. Its components are intended to be shared at the source level, rather than being a library that gets built, installed, and linked against. Thus, there is no distribution tarball; the idea is to copy files from Gnulib into your own source tree.

Now I didn't want to actually copy source code, so I settled on a submodule as a compromise. However, if it turns out that people are using gnulib as a library rather than as a "source dependency", I'm definitely open to changing that.

**Comment by anoopcs9** [comment]
You are absolutely right. I somehow missed that point. This came to my attention as I was doing my preparations for packaging glusterfs-coreutils as per fedora guidelines. Even if we are having a bundled dependency we can still cope with that by adding Provides: to spec file [bundling libraries:](https://fedoraproject.org/wiki/Packaging:Guidelines?rd=Packaging/Guidelines#Bundling_and_Duplication_of_system_libraries)

> Fedora packages should make every effort to avoid having multiple, separate, upstream projects bundled together in a single package. All packages whose upstreams allow them to be built against system libraries must be built against system libraries. All packages whose upstreams have no mechanism to build against system libraries may opt to carry bundled libraries, but if they do, they must include Provides: bundled(<libname>) = <version> in their RPM spec file. In addition, packages whose upstreams have no mechanism to build against system libraries must be contacted publicly about a path to supporting system libraries. If upstream refuses, this must be recorded in the spec file, either in comments placed adjacent to the Provides: above, or in an additional file checked into the SCM and referenced by a comment placed adjacent to the Provides: above.

But before closing I would like to hear from @nixpanic on how to go about this issue while preparing packages for fedora.

**Comment by nixpanic** [comment]
Indeed, Fedora packages are not supposed to have bundled libraries. If upstream projects use these, it is recommended to delete the sources in the `%prep` step and apply a patch to the build scripts to use the library and headers provided in the distribution.

I guess it would be nice to have the option in the build script for glusterfs-coreutils. In case there are headers provided by the distribution for gnulib, use those, otherwise fall-back to the bundled git-submodule.

**Comment by anoopcs9** [comment]
Thanks for your input. I will do the necessary changes.
